backend:
  name: github
  repo: USERNAME/REPO_NAME
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "ข่าวสาร"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "หัวข้อข่าว", name: "title", widget: "string" }
      - { label: "วันที่", name: "date", widget: "datetime" }
      - { label: "เนื้อหา", name: "body", widget: "markdown" }
